### PR TITLE
Bumped Roxygen version.

### PR DESCRIPTION
**Pull request by CGMossa**
Added documentation files, otherwise they are not present when people install this from github.

There was no documentation to be found when I installed this from github. With this, one
gets the documentation readily with `devtools::install_github(...)`.

### CODE REVIEW

**Comment by CGMossa** [comment]
Right! Here's a way to access this version and see that it does indeed affect help-files.

```r 
install_github("CGMossa/gnumaker", ref="documentation")
help("create_makefile", package = gnumaker)
```

**Comment by petebaker** [comment]
Hi Mossa

Thanks for bringing this to my attention and thanks for the fix!

This is a nice way to fix the problem but is my mistake in the first place. I really should just have added all files in **man/** directory which seems to be the standard thing to do. Now done and bumped **gnumaker** version so will close the pull request unless you find any problems with this approach

Thanks again!

Cheers
Peter

**Comment by CGMossa** [comment]
Nope, I agree that this is better that you do it directly. I just wanted to show-case the issue via the PR. 

I love this! I've never really contributed before, but it is working soo smoothly.
Have a nice weekend

**Comment by petebaker** [comment]
Thanks for your suggestions. It really is great that we can collaborate from the opposite side of the globe and I greatly appreciate your input!

I hope you had a nice weekend too! Glorious cool sunny days below 30. Brisbane is great 3 seasons of the year - just not summer. Cheers Peter

**Comment by petebaker** [comment]
Oops. I now see that's what you did - my apologies - I should have accepted the pull request - just haven't had one before. Will try harder next time. 
Thanks again

**Review by petebaker — COMMENTED** [review]
Looks good

**Pull request closed without merging**
